### ISSUE TITLE
Behat

### ISSUE THREAD

**Issue by garhbod** [cmderdev/cmder#838]
When running behat through cmder some of the printed text is the same color as the background and it can't be read.

I have tried changing colours and themes but nothing works

**Comment by MartiUK** [comment]
Try running behat with `--no-ansi` 
http://docs.behat.org/en/v3.0/guides/7.run.html

**Comment by garhbod** [comment]
There is no `--no-ansi` option
There is a `--no-color` option
But that doesn't really fix the issue that cmder has

**Comment by Comanche** [comment]
Any fix on this?

If you dump the output to file using `behat > behat.log` or `behat --out behat.log` then display the contents of the file using `type behat.log` or `cat behat.log`, all colors are correct.

However, if you simply run `behat`, colors are not working properly.

**Comment by Comanche** [comment]
[ansicon](https://github.com/adoxa/ansicon) seems to display the colors correctly.

**Comment by Comanche** [comment]
A workaround is to explicitly set the styles in `behat.yml`:

```yml
default:
    formatters:
        pretty:
            parameters:
            output_styles:
                keyword:       [ default, null, [ bold ] ]
                comment:       [ magenta, null]
```
